#!/usr/bin/env python3
"""Renders the IBM-i-Execution-Results wiki page: what each test program
displayed when it ran on a real IBM i, next to what it displays with rpgc,
and — for each difference — why.

What IBM displayed comes from ibmi-execution-baseline.json, which
scripts/ibmi-execution.sh refreshes; what rpgc displays is
tests/expected_output/; why they differ is tests/ibmi-execution-notes.txt,
kept by hand. The comparison is execution-diff.py's, so this page and
ibmi-execution-differences.md always agree.

The IBM i conformance workflow's `execute` mode runs this after each run and
pushes the page to the wiki. Locally:

  scripts/execution-wiki.py --out /path/to/OpenRPG.wiki/IBM-i-Execution-Results.md \\
      --sidebar /path/to/OpenRPG.wiki/_Sidebar.md
"""
import argparse, datetime, difflib, importlib.util, json, os, re, subprocess

ap = argparse.ArgumentParser()
ap.add_argument("--baseline", default="ibmi-execution-baseline.json")
ap.add_argument("--tests", default="tests")
ap.add_argument("--notes", default="tests/ibmi-execution-notes.txt")
ap.add_argument("--out", default="IBM-i-Execution-Results.md")
ap.add_argument("--commit", default="", help="commit the run verified (default: HEAD)")
ap.add_argument("--run-url", default="", help="link to the workflow run")
ap.add_argument("--repo", default="danlong005/OpenRPG")
ap.add_argument("--sidebar", default="", help="the wiki's _Sidebar.md: add a link to this page if missing")
a = ap.parse_args()

# The comparison itself lives in execution-diff.py (a hyphenated name, so
# loaded by path).
_spec = importlib.util.spec_from_file_location(
    "execution_diff", os.path.join(os.path.dirname(os.path.abspath(__file__)), "execution-diff.py"))
xd = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(xd)

commit = a.commit
if not commit:
    try:
        commit = subprocess.check_output(["git", "rev-parse", "HEAD"], text=True).strip()
    except Exception:
        commit = ""

baseline = json.load(open(a.baseline))
files = baseline["files"]
skipped = [tuple(s) for s in baseline.get("skipped", [])
           if s[0] not in files and os.path.exists(os.path.join(a.tests, s[0]))]

notes = {}
if os.path.exists(a.notes):
    for ln in open(a.notes):
        ln = ln.rstrip("\n")
        if not ln.strip() or ln.lstrip().startswith("#"):
            continue
        parts = ln.split(None, 2)
        if len(parts) == 3:
            notes[parts[0]] = (parts[1], parts[2])

CATEGORY = {
    "rpgc": "rpgc differs from IBM i: work to do",
    "platform": "Differs by design, following from the platform",
    "test": "The test relies on something IBM i does not do",
    "open": "Cause not established yet",
    None: "Not yet investigated",
}
RESULT = {
    "same": "✅ same",
    "same-error": "✅ same, then both end in an error",
    "differs": "❌ output differs",
    "runtime-error": "❌ error on IBM i",
    "timeout": "❌ did not finish on IBM i",
    "compile-failed": "❌ did not compile",
    "no-expected-output": "— no rpgc output to compare",
    "stale": "— changed since it ran",
    "removed": "— test removed",
}
OK = ("same", "same-error")
DIFF = ("differs", "runtime-error", "timeout", "compile-failed")


def cell(s):
    return (str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            .replace("|", "\\|").replace("\n", " ").strip())


def short(name):
    return os.path.splitext(name)[0]


def anchor(name):
    return re.sub(r"[^a-z0-9_-]", "", short(name).lower())


def src_link(name, label=None):
    label = label or f"`{name}`"
    if not commit:
        return label
    return f"[{label}](https://github.com/{a.repo}/blob/{commit}/tests/{name})"


def natural(name):
    return [int(t) if t.isdigit() else t.lower() for t in re.split(r"(\d+)", name)]


rows = []
for n in sorted(files, key=natural):
    e = files[n]
    src = os.path.join(a.tests, n)
    cls = xd.classify(e, a.tests, xd.sha(src)) if os.path.exists(src) else "removed"
    rows.append((n, e, cls))

# ---- should it match? --------------------------------------------------------
# Every program should display the same on IBM i as with rpgc, except where
# the platform makes them differ by design: those are the notes' "platform"
# entries (a pointer is 16 bytes on IBM i, a hex literal is EBCDIC there, ...).
def should_match(n):
    return notes.get(n, (None, ""))[0] != "platform"

compared = [r for r in rows if r[2] in OK or r[2] in DIFF]
matched = {n for n, e, cls in compared if cls in OK}
diff = [r for r in compared if r[2] in DIFF]
expect = {n: should_match(n) for n, _, _ in compared}
as_expected = [n for n, _, _ in compared if expect[n] == (n in matched)]
rated = [n for n, _, _ in compared if expect[n]]
agree = [n for n in rated if n in matched]
rating = 100.0 * len(agree) / len(rated) if rated else 0.0

out = []
w = out.append
now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
w("# IBM i Execution Results\n")
w("> Generated by the **IBM i conformance** workflow's `execute` mode "
  "(`scripts/execution-wiki.py`) after each run. Do not edit this page by hand; it is "
  "overwritten. Why each program differs comes from [`tests/ibmi-execution-notes.txt`]"
  f"(https://github.com/{a.repo}/blob/main/tests/ibmi-execution-notes.txt): edit it there.\n")
w("Every test program that runs on its own is compiled with IBM's ILE RPG compiler on "
  "a real IBM i **and run there**, and what it displays is compared line by line with "
  "what the same program displays compiled with rpgc. "
  "[IBM i Conformance Results](IBM-i-Conformance-Results) shows whether IBM compiles "
  "each program; this page shows whether it then **does the same thing**. rpgc's "
  "expected outputs are written by rpgc itself, so IBM i is the only independent check "
  "of what the programs do.\n")

w("## Execution rating\n")
w(f"# {rating:.1f}%\n")
w(f"**{len(agree)} of {len(rated)}** programs that should run the same on IBM i as with "
  "rpgc do: they display exactly the same output. Trailing blanks are ignored (DSPLY "
  "does not show them); nothing else is.\n")
w("**What this rating means:** it counts the programs that should behave the same on "
  "both platforms. A program that differs **by design** — because the system it runs on "
  "differs (a pointer is 16 bytes on IBM i, a hex literal is EBCDIC there, a parser "
  "rpgc builds in is a separate program on IBM i) — is expected to differ, and is not "
  "counted against the rating. The reason for each is under Details.\n")
w("| | Programs |")
w("|---|---|")
w(f"| Should run the same, and do | {len(agree)} |")
w(f"| Should run the same, and do not ⚠️ | {len(rated) - len(agree)} |")
w(f"| Differ by design (the platform) | {sum(1 for n in expect if not expect[n])} |")
w("")
w("| | |")
w("|---|---|")
w(f"| Page generated | {now} |")
if baseline.get("generated"):
    w(f"| Last run on IBM i | {baseline['generated']} |")
if commit:
    w(f"| Source | [`{commit[:7]}`](https://github.com/{a.repo}/commit/{commit}) |")
if a.run_url:
    w(f"| Workflow run | [{a.run_url.rsplit('/', 1)[-1]}]({a.run_url}) |")
w("")

w("## Summary\n")
sm = lambda want, got: sum(1 for n in expect if expect[n] == want and (n in matched) == got)
w("| | Same on IBM i | Differs | Total |")
w("|---|---|---|---|")
w(f"| **Should run the same** | {sm(True, True)} | {sm(True, False)} | {sm(True, True) + sm(True, False)} |")
w(f"| **Differs by design** | {sm(False, True)} | {sm(False, False)} | {sm(False, True) + sm(False, False)} |")
w(f"| Total | {len(matched)} | {len(diff)} | {len(compared)} |")
w("")
w(f"**{len(as_expected)} of {len(compared)} programs behave as expected on IBM i.** The "
  f"other {len(compared) - len(as_expected)} are marked ⚠️ below: rpgc does something "
  "IBM i does not (work to do), the test relies on something IBM i does not do, or the "
  "cause is not established yet. A program that differs by design but ran the same "
  "would be marked too: its note is out of date.\n")
if skipped:
    w(f"{len(skipped)} run tests are not run on IBM i; see [Not run](#not-run).\n")

w("### Why the others differ\n")
by_cat = {}
for n, e, cls in diff:
    by_cat.setdefault(notes.get(n, (None, ""))[0], []).append(n)
w("| Cause | Programs |")
w("|---|---|")
for cat in ("rpgc", "test", "open", None, "platform"):
    if by_cat.get(cat):
        w(f"| {CATEGORY[cat]} | {len(by_cat[cat])} |")
w("")

def yes_no(v):
    return "✅" if v else "❌"

# The table holds only short cells, so it fits the page: long text (the
# reason, IBM's error, the output) is in Details, linked from its row. With
# long text in the table GitHub cuts off the right-hand columns.
def ibm_ran(e):
    """How the program ran on IBM i."""
    s = e.get("status")
    if s == "timeout":
        return "⏱"
    return "❌" if s in ("runtime-error", "compile-failed") else "✅"


def rpgc_ran(e):
    """How the program runs compiled with rpgc: its recorded output ends in the
    runtime error that stopped it, if one did."""
    lines = xd.norm(xd.expected_lines(a.tests, e["test"]) or [])
    return "❌" if lines and re.match(r"RNX\d{4}", lines[-1]) else "✅"


w(f"## All programs ({len(rows)})\n")
w("**IBM i** and **rpgc**: how the program ran compiled by each — ✅ to the end, "
  "❌ it ended in an error, ⏱ it did not finish. **Same output**: ✅ it displayed the "
  "same on both, ❌ it did not. ⚠️ marks a result that differs from what the program "
  "should do.\n")
w("| Program | Should match | IBM i | rpgc | Same output | | Details | Last run |")
w("|---|:-:|:-:|:-:|:-:|:-:|---|---|")
detailed = []
for n, e, cls in rows:
    if n not in expect:
        w(f"| {src_link(n, short(n))} | | | | {RESULT.get(cls, cls)} | | | {e.get('verified', '—')} |")
        continue
    want, got = expect[n], n in matched
    has_detail = (not got) or (not want)
    if has_detail:
        detailed.append((n, e, cls))
    w(f"| {src_link(n, short(n))} | {'Yes' if want else 'No'} | {ibm_ran(e)} | {rpgc_ran(e)} | "
      f"{yes_no(got)} | {'' if want == got else '⚠️'} | "
      f"{f'[why](#{anchor(n)})' if has_detail else ''} | {e.get('verified', '—')} |")
w("")

w(f"## Details ({len(detailed)})\n")
w("For each program that differs, or is expected to: why, IBM's error if the program "
  "ended in one, and the output side by side — lines only rpgc displays are marked "
  "`-`, lines only IBM i displays `+`.\n")
for n, e, cls in detailed:
    cat, why = notes.get(n, (None, ""))
    want, got = expect[n], n in matched
    w(f"### {short(n)}\n")
    w(f"{src_link(n)} — should {'run the same' if want else 'differ by design'}; "
      + ("it did." if want == got else "it did not. ⚠️") + "\n")
    w(f"**{CATEGORY[cat]}**" + (f": {cell(why)}" if why else ".") + "\n")
    if e.get("error"):
        w(f"IBM i: `{cell(e['error'])}`\n")
    if cls == "compile-failed":
        w("```")
        out.extend(e.get("listing", [])[:20])
        w("```\n")
        continue
    exp = xd.norm(xd.expected_lines(a.tests, e["test"]) or [])
    got_lines = xd.norm(e["output"])
    lines = list(difflib.unified_diff(exp, got_lines, "rpgc", "IBM i", lineterm="", n=2))
    if lines:
        w("```diff")
        out.extend(lines)
        w("```\n")
    elif cls not in OK:
        w("The displayed output is the same; only the ending differs.\n")

if skipped:
    w("## Not run\n")
    w("Run tests the harness does not run on IBM i, and why.\n")
    w("| Program | Why |")
    w("|---|---|")
    for n, why in skipped:
        w(f"| {src_link(n, short(n))} | {cell(why)} |")
    w("")

open(a.out, "w").write("\n".join(out) + "\n")

# Reachable from the wiki's sidebar, after the conformance page's entry.
if a.sidebar and os.path.exists(a.sidebar):
    side = open(a.sidebar).read()
    entry = "- [IBM i Execution Results](IBM-i-Execution-Results)"
    if "(IBM-i-Execution-Results)" not in side:
        conf = "- [IBM i Conformance Results](IBM-i-Conformance-Results)"
        side = side.replace(conf, conf + "\n" + entry, 1) if conf in side \
            else side.rstrip("\n") + "\n" + entry + "\n"
        open(a.sidebar, "w").write(side)

print(f"wrote {a.out}: rating {rating:.1f}% ({len(agree)} of {len(rated)}); "
      f"{len(as_expected)} of {len(compared)} as expected; "
      f"{sum(1 for n, _, _ in diff if n not in notes)} differences with no cause recorded")
