#!/usr/bin/env python3
"""Renders the IBM-i-Execution-Results wiki page: what each test program
displayed when it ran on a real IBM i, next to what it displays with rpgc,
and -- for each difference -- why.

What IBM displayed comes from ibmi-execution-baseline.json, which
scripts/ibmi-execution.sh refreshes; what rpgc displays is
tests/expected_output/; why they differ is tests/ibmi-execution-notes.txt,
kept by hand. The comparison is execution-diff.py's, so this page and
ibmi-execution-differences.md always agree.

The IBM i conformance workflow's `execute` mode runs this after each run and
pushes the page to the wiki. Locally:

  scripts/execution-wiki.py --out /path/to/OpenRPG.wiki/IBM-i-Execution-Results.md \\
      --sidebar /path/to/OpenRPG.wiki/_Sidebar.md
"""
import argparse, datetime, difflib, importlib.util, json, os, re, subprocess

ap = argparse.ArgumentParser()
ap.add_argument("--baseline", default="ibmi-execution-baseline.json")
ap.add_argument("--tests", default="tests")
ap.add_argument("--notes", default="tests/ibmi-execution-notes.txt")
ap.add_argument("--out", default="IBM-i-Execution-Results.md")
ap.add_argument("--commit", default="", help="commit the run verified (default: HEAD)")
ap.add_argument("--run-url", default="", help="link to the workflow run")
ap.add_argument("--repo", default="danlong005/OpenRPG")
ap.add_argument("--sidebar", default="", help="the wiki's _Sidebar.md: add a link to this page if missing")
a = ap.parse_args()

# The comparison itself lives in execution-diff.py (a hyphenated name, so
# loaded by path).
_spec = importlib.util.spec_from_file_location(
    "execution_diff", os.path.join(os.path.dirname(os.path.abspath(__file__)), "execution-diff.py"))
xd = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(xd)

commit = a.commit
if not commit:
    try:
        commit = subprocess.check_output(["git", "rev-parse", "HEAD"], text=True).strip()
    except Exception:
        commit = ""

baseline = json.load(open(a.baseline))
files = baseline["files"]
skipped = [tuple(s) for s in baseline.get("skipped", [])
           if s[0] not in files and os.path.exists(os.path.join(a.tests, s[0]))]

notes = {}
if os.path.exists(a.notes):
    for ln in open(a.notes):
        ln = ln.rstrip("\n")
        if not ln.strip() or ln.lstrip().startswith("#"):
            continue
        parts = ln.split(None, 2)
        if len(parts) == 3:
            notes[parts[0]] = (parts[1], parts[2])

CATEGORY = {
    "rpgc": "rpgc differs from IBM i: work to do",
    "platform": "Differs by design, following from the platform",
    "test": "The test relies on something IBM i does not do",
    "open": "Cause not established yet",
    None: "Not yet investigated",
}
RESULT = {
    "same": "✅ same",
    "same-error": "✅ same, then both end in an error",
    "differs": "❌ output differs",
    "runtime-error": "❌ error on IBM i",
    "timeout": "❌ did not finish on IBM i",
    "compile-failed": "❌ did not compile",
    "no-expected-output": "— no rpgc output to compare",
    "stale": "— changed since it ran",
    "removed": "— test removed",
}
OK = ("same", "same-error")


def cell(s):
    return (str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            .replace("|", "\\|").replace("\n", " ").strip())


def short(name):
    return os.path.splitext(name)[0]


def anchor(name):
    return re.sub(r"[^a-z0-9_-]", "", short(name).lower())


def gh_slug(heading):
    """The id GitHub gives a heading: lower case, punctuation dropped, spaces
    to hyphens."""
    s = re.sub(r"[^\w\- ]", "", heading.lower())
    return s.replace(" ", "-")


def src_link(name, label=None):
    label = label or f"`{name}`"
    if not commit:
        return label
    return f"[{label}](https://github.com/{a.repo}/blob/{commit}/tests/{name})"


def natural(name):
    return [int(t) if t.isdigit() else t.lower() for t in re.split(r"(\d+)", name)]


rows = []
for n in sorted(files, key=natural):
    e = files[n]
    src = os.path.join(a.tests, n)
    cls = xd.classify(e, a.tests, xd.sha(src)) if os.path.exists(src) else "removed"
    rows.append((n, e, cls))

same = [r for r in rows if r[2] in OK]
diff = [r for r in rows if r[2] in ("differs", "runtime-error", "timeout", "compile-failed")]
compared = [r for r in rows if r[2] in OK or r in diff]
pct = 100.0 * len(same) / len(compared) if compared else 0.0

out = []
w = out.append
now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
w("# IBM i Execution Results\n")
w("> Generated by the **IBM i conformance** workflow's `execute` mode "
  "(`scripts/execution-wiki.py`). Do not edit this page by hand; it is overwritten. "
  "The causes come from [`tests/ibmi-execution-notes.txt`]"
  f"(https://github.com/{a.repo}/blob/main/tests/ibmi-execution-notes.txt): edit them there.\n")
w("Every test program that runs on its own is compiled with IBM's ILE RPG compiler "
  "on a real IBM i **and run there**, and what it displays is compared line by line "
  "with what the same program displays when compiled with rpgc. "
  "[IBM i Conformance Results](IBM-i-Conformance-Results) asks whether IBM compiles a "
  "program; this page asks whether it then **does the same thing**. rpgc's expected "
  "outputs are written by rpgc itself, so IBM i is the only independent check of "
  "behaviour the project has.\n")
w("## Result\n")
w(f"# {len(same)} of {len(compared)} ({pct:.1f}%)\n")
w(f"run tests display exactly what they display on IBM i. Trailing blanks are "
  "ignored (DSPLY does not show them); nothing else is.\n")
w("| | |")
w("|---|---|")
w(f"| Page generated | {now} |")
if baseline.get("generated"):
    w(f"| Last run on IBM i | {baseline['generated']} |")
if commit:
    w(f"| Source | [`{commit[:7]}`](https://github.com/{a.repo}/commit/{commit}) |")
if a.run_url:
    w(f"| Workflow run | [{a.run_url.rsplit('/', 1)[-1]}]({a.run_url}) |")
w("")

w("## Summary\n")
w("| Result | Programs |")
w("|---|---|")
for key in RESULT:
    c = sum(1 for r in rows if r[2] == key)
    if c:
        w(f"| {RESULT[key]} | {c} |")
if skipped:
    w(f"| — not run on IBM i (see [Not run](#not-run)) | {len(skipped)} |")
w("")

w("## Differences by cause\n")
w("Each difference has a cause recorded in `tests/ibmi-execution-notes.txt`, or "
  "none yet. **rpgc** entries are the work queue.\n")
by_cat = {}
for n, e, cls in diff:
    by_cat.setdefault(notes.get(n, (None, ""))[0], []).append(n)
w("| Cause | Programs |")
w("|---|---|")
for cat in ("rpgc", "open", None, "test", "platform"):
    if by_cat.get(cat):
        w(f"| [{CATEGORY[cat]}](#{gh_slug(CATEGORY[cat])}) | {len(by_cat[cat])} |")
w("")
for cat in ("rpgc", "open", None, "test", "platform"):
    ns = by_cat.get(cat)
    if not ns:
        continue
    w(f"### {CATEGORY[cat]}\n")
    for n in ns:
        why = notes.get(n, (None, ""))[1]
        w(f"- [{short(n)}](#{anchor(n)}) — {cell(why) if why else 'no note yet'}")
    w("")

# A narrow table: long text lives in Details, linked from its row, so GitHub
# does not cut off the right-hand columns (as it did on the conformance page).
w(f"## All programs ({len(rows)})\n")
w("| Program | Result | Cause | Details | Last run |")
w("|---|---|---|---|---|")
for n, e, cls in rows:
    bad = (n, e, cls) in diff
    cat = notes.get(n, (None, ""))[0] if bad else None
    w(f"| {src_link(n, short(n))} | {RESULT.get(cls, cls)} | "
      f"{(cat or 'not investigated') if bad else ''} | "
      f"{f'[why](#{anchor(n)})' if bad else ''} | {e.get('verified', '—')} |")
w("")

w(f"## Details ({len(diff)})\n")
w("For each program that differs: the cause, IBM's error if the program ended in one, "
  "and the output side by side as a diff — lines only rpgc displays are marked `-`, "
  "lines only IBM i displays `+`.\n")
for n, e, cls in diff:
    cat, why = notes.get(n, (None, ""))
    w(f"### {short(n)}\n")
    w(f"{src_link(n)} — {RESULT.get(cls, cls)}. "
      f"**{CATEGORY[cat]}**" + (f": {cell(why)}" if why else ".") + "\n")
    if e.get("error"):
        w(f"IBM i: `{cell(e['error'])}`\n")
    if cls == "compile-failed":
        w("```")
        out.extend(e.get("listing", [])[:20])
        w("```\n")
        continue
    exp = xd.norm(xd.expected_lines(a.tests, e["test"]) or [])
    got = xd.norm(e["output"])
    lines = list(difflib.unified_diff(exp, got, "rpgc", "IBM i", lineterm="", n=2))
    if lines:
        w("```diff")
        out.extend(lines)
        w("```\n")
    else:
        w("The displayed output is the same; only the ending differs.\n")

if skipped:
    w("## Not run\n")
    w("Run tests the harness does not run on IBM i, and why.\n")
    w("| Program | Why |")
    w("|---|---|")
    for n, why in skipped:
        w(f"| {src_link(n, short(n))} | {cell(why)} |")
    w("")

open(a.out, "w").write("\n".join(out) + "\n")

# Reachable from the wiki's sidebar, after the conformance page's entry.
if a.sidebar and os.path.exists(a.sidebar):
    side = open(a.sidebar).read()
    entry = "- [IBM i Execution Results](IBM-i-Execution-Results)"
    if "(IBM-i-Execution-Results)" not in side:
        conf = "- [IBM i Conformance Results](IBM-i-Conformance-Results)"
        side = side.replace(conf, conf + "\n" + entry, 1) if conf in side \
            else side.rstrip("\n") + "\n" + entry + "\n"
        open(a.sidebar, "w").write(side)

print(f"wrote {a.out}: {len(same)} of {len(compared)} the same; "
      f"{len(diff)} differ ({sum(1 for n, _, _ in diff if n not in notes)} with no cause recorded)")
